FROM mcr.microsoft.com/dotnet/runtime:10.0

RUN apt-get update && apt-get -y install \
    libopus0 \
    opus-tools \
    libopus-dev \
    libsodium-dev \
    ffmpeg \
    python3 \
    python3-pip \
    && pip3 install --break-system-package -U yt-dlp curl-cffi