name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish --configuration Release
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Zip build artifact
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r /bin/Release/net6.0/publish bingbot
      - uses: actions/upload-artifact@v2
        with:
          name: bingbot.zip
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bingbot.zip
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "bingbot.zip"
          target: "/var/"
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              cd /var/
              unzip bingbot.zip && rm bingbot.zip
              cd bingbot
              sudo pkill _bingbot
              dotnet run &
